//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace prjCustomer.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    
    public partial class tCustomer
    {
        public int fId { get; set; }
        [DisplayName("客戶姓名")]
        [Required]
        public string fName { get; set; }
        [DisplayName("手機電話")]
        [RegularExpression(@"[0-9]{10}",ErrorMessage ="電話號碼必須十個字")]
        public string fPhone { get; set; }
        [DisplayName("客戶地址")]
        [Required]
        public string fAddress { get; set; }
    }
}
